### ISSUE TITLE
Programmatically add the right amount of fragments

### ISSUE THREAD

**Issue by gcalmettes** [ptamarit/slides-data-viz-web-d3#2]
The Reveal-to-D3 addition is awesome. Have you given some thoughts on how to programmatically add the right amount of fragments in the slides given the number of functions in the config by any chance?
Thanks!

**Comment by ptamarit** [comment]
Thanks!

I checked and didn't find any Reveal API to programmatically add fragments to a slide.

But then it's just an HTML document, so for sure you can manipulate the DOM with JS and add some fragment nodes where you want during the initialization phase.
Now, if Reveal kicks in before you manipulate the DOM, I'm not sure that Reveal will detect the fact that the DOM changed after the fact; this needs to be tested.

If this works, then it sounds doable to write a little script which goes through each entry in the config, count the number of functions, find the corresponding slide in the DOM and add the right amount of fragments.

Please let me know how it goes.

**Comment by gcalmettes** [comment]
Thanks, I will investigate and try to play around those lines!
Will let you know how it goes.

**Comment by ptamarit** [comment]
Hey @gcalmettes,

Looks like somebody created a plugin which does just what you want:
https://github.com/jlegewie/reveal.js-d3js-plugin

I'll close this issue.

Cheers,
Pablo

**Comment by gcalmettes** [comment]
Indeed, the plugin looks great! Thanks @ptamarit for showing us how to integrate D3 transition into Reveal presentations in the first place!
